apiVersion: v1
kind: PersistentVolume
metadata:
  name: external-quiz-db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: C:\Users\camac\OneDrive\Desktop\money-quiz\frontend
