# password-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: password-form
spec:
  selector:
    app: password
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP

