apiVersion: v1
kind: Service
metadata:
  name: backend-db-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5432  # Use the same port as your PostgreSQL database
  type: LoadBalancer
