apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-app-volume
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: frontend-app-volume
        persistentVolumeClaim:
          claimName: frontend-app-pvc
